export enum EnvCollection {
    DB_NAME = "DB_NAME",
    DB_HOST = "DB_HOST",
    DB_PORT = "DB_PORT",
    DB_USER = "DB_USER",
    DB_PASSWORD = "DB_PASSWORD",
    DATABASE_URL = "DATABASE_URL",
    ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET",
    REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET",
}